# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: wy-app-CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - '.gitignore'
    - '.dockerignore'
  
jobs:
  node-CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set Variables
      id: set-var
      run: |
        echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV
        echo "ECR_REPOSITORY=byeol-web" >> $GITHUB_ENV
        echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV
        echo "GIT_EMAIL=skystar20095@gmail.com" >> $GITHUB_ENV
        echo "GIT_NAME=skystar200" >> $GITHUB_ENV
    
    - name: Use Node.js v21.6
      uses: actions/setup-node@v3
      with:
        node-version: '21.6'
        cache: 'npm'
        cache-dependency-path: './node-app/package-lock.json'

    - name: Setup Node.js environment
      working-directory: ./node-app/
      run: |
        npm ci
        npm run build --if-present
        npm test
        
    - name: Docker Image Build
      id: build-image
      working-directory: ./node-app/
      run: |
        docker build -t ${{ env.ECR_REGISTRY }}/${{ env. ECR_REPOSITORY }}:${{env.IMAGE_TAG}} .

    - name: Docker Image Push
      id: push-image
      run: |
        docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY}}:${{ env.IMAGE_TAG }}

    - name: Checkout Deployment Repository
      uses: actions/checkout@v3
      with:
        repository: skystar200/wy-dep
        ref: main
        token: ${{ secrets.GH_TOKEN }}

    - name: k8s manifest update
      run: |
        sed -i "s@ \
        image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:.*@ \
        image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG}}@g" node-deployment.yml

    - name: Commit and Push
      run: |
        git config user.email ${{ env.GIT_EMAIL }}
        git config user.name ${{ env.GIT_NAME}}
        git add node-deployment.yml
        git commit -m "Update image tag"
        git push origin main
